apiVersion: v1
kind: Service
metadata:
  name: eshop-stable-svc
  namespace: default
  labels:
    app: eshop
spec:
  selector:
    app: eshop
    version: stable
  ports:
  - name: web
    port: 80
    targetPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: eshop-canary-svc
  namespace: default
  labels:
    app: eshop
spec:
  selector:
    app: eshop
    version: canary
  ports:
  - name: web
    port: 80
    targetPort: 4000